### PR TITLE
plugins/target/aws-asg: correctly order region config setting.

### LINKED ISSUE #472: `aws_region` not respected
## The Bug

Upon setting the `aws_region` config setting in the autoscaler config, we noticed that it didn't actually seem to be respected by the autoscaler. Instead it seemed to default to the region that the instance was currently deployed in. After further debugging, we also found that we could affect the region by setting `AWS_DEFAULT_REGION` in the autoscaler's environment. 

## Context

We are setting three different plugin instances, all using `aws-asg` as driver, and each with a different `aws_region` set. Only the plugin dispensed with the `aws_region` set to it's home region ended up working. The other two fail with the following:
```log
failed to describe AWS Autoscaling Group: expected 1 Autoscaling Group, got 0
```

We also did some source diving and patched in a few extra logger statements so that we could determine that the region is not being set properly. Here is some output from our custom logger to show more clearly the issue:

```log
Dispense plugin: client-us-east-2-c5-4xlarge
external_plugin.aws-asg: ASG client region: eu-central-1
```

Here you can see we are dispensing plugin intended for us-east-2 region, with it's `aws_region` being likewise set, yet logging the actual value of the region at that point in the code shows it is still using eu-cental-1 regardless of the config setting.

### PR DESCRIPTION
**Pull request by jrasell**
A user specific region configuration option should take precedence
over other options. This change therefore updates the flow in
which the AWS config is populated. In situation where AWS and the
operator do not provide an option, the default is applied.

The change itself is hard to automatically test at the moment as
the behaviour changes depending whether you have the EC2 metadata
service available. The test added is aimed at situations where the
plugin is not running with the EC2 metadata service available.

#473 has been raised to track better testing where the EC2 metadata
service is available.

closes #472

### CODE REVIEW

File: plugins/builtin/target/aws-asg/plugin/aws_test.go [hunk 1]
```diff
@@ -2,15 +2,56 @@ package plugin
...
+	hclog "github.com/hashicorp/go-hclog"
 	"github.com/hashicorp/nomad-autoscaler/sdk/helper/scaleutils"
 	"github.com/hashicorp/nomad/api"
 	"github.com/stretchr/testify/assert"
 )
 
+func TestTargetPlugin_SetConfig_NonAWS(t *testing.T) {
+	if os.Getenv("NOMAD_AUTOSCALER_AWS") != "" {
+		t.Skip("skipping aws-asg non-aws environment test, NOMAD_AUTOSCALER_AWS set")
+	}
```
Comment (jrasell) [inline plugins/builtin/target/aws-asg/plugin/aws_test.go:19]: this test will only pass where the EC2 metadata is not available; therefore I have added this placeholder as a reminder when adding additional tests that we could use an env var to control which get run depending on the situation.

**Review by lgfa29 — APPROVED** [review]
Oof, nice catch!
