### PR TITLE
Allow fixed-value autoscaling without APM availability

### LINKED ISSUE #1260: [error] failed to query source: unsupported query type
### Nomad Autoscaler version
Nomad Autoscaler v0.4.9 (82611d2)
Nomad v1.11.3

### Operating system and Environment details
Linux HashiCarp 6.12.73-v8+ #1947 SMP PREEMPT Thu Feb 19 12:31:05 GMT 2026 aarch64 GNU/Linux
Docker Version: 29.3.0

### Issue
A simple policy that worked on previous version now fails with an error message "failed to query source: unsupported query type".

### Reproduction steps
Run a nomad job with the following scaling block and Nomad Autoscaler will report errors.
```
    scaling {
      enabled = true
      min     = 1
      max     = 10

      policy {
        check "fixed-value-check" {
          strategy "fixed-value" {
            value = 2
          }
        }
      }
    }
```

#### Expected Result
Expected policy to evaluate successfully. (as previous versions did.)

#### Actual Result
```
[ERROR] policy_manager: encountered an error monitoring policy IDs: error="handler: unable to execute policy ID: 9851171e-7760-4d02-b792-632401bca43b, failed get count from metrics: failed to query source: failed to query source: unsupported query type \"\""
```

### Job file (if appropriate)
```
job "webapp" {
  datacenters = ["dc1"]

  group "demo" {
    network {
      mode = "host"
      port "http" {
      }
    }

    service {
      port = "http"
      name = "webapp"
      tags = ["urlprefix-webapp.service.consul/"]
      check {
        port     = "http"
        type     = "http"
        path     = "/"
        method   = "HEAD"
        interval = "10s"
        timeout  = "2s"
      }
    }

    task "app" {
      driver = "docker"

      config {
        image = "hashicorp/http-echo:1.0"
        ports = ["http"]
        args = [
          "-listen", ":${NOMAD_PORT_http}",
        ]
      }
    }
    scaling {
      enabled = true
      min     = 1
      max     = 10

      policy {
        check "fixed-value-check" {
          strategy "fixed-value" {
            value = 2
          }
        }
      }
    }
  }
}
```

### Nomad Autoscaler logs
```
2026-03-22T23:04:14.230Z [INFO]  agent: starting Nomad Autoscaler agent
2026-03-22T23:04:14.231Z [INFO]  agent: Nomad Autoscaler agent configuration:
2026-03-22T23:04:14.231Z [INFO]  agent
2026-03-22T23:04:14.231Z [INFO]  agent:         Bind Addrs: 0.0.0.0
2026-03-22T23:04:14.231Z [INFO]  agent:  High Availability: true
2026-03-22T23:04:14.231Z [INFO]  agent:          Log Level: info
2026-03-22T23:04:14.231Z [INFO]  agent:            Plugins: //plugins
2026-03-22T23:04:14.231Z [INFO]  agent:           Policies: 
2026-03-22T23:04:14.231Z [INFO]  agent:            Version: v0.4.9 (82611d2)
2026-03-22T23:04:14.231Z [INFO]  agent
2026-03-22T23:04:14.231Z [INFO]  agent: Nomad Autoscaler agent started! Log data will stream in below
2026-03-22T23:04:14.249Z [INFO]  agent: running in HA mode: lock_namespace=default lock_path=nomad/jobs/autoscaler/nomad/lock lock_ttl=1m0s lock_delay=30s
2026-03-22T23:04:14.249Z [INFO]  agent.http_server: server now listening for connections: address=0.0.0.0:27729
2026-03-22T23:04:14.258Z [INFO]  agent.plugin_manager: successfully launched and dispensed plugin: plugin_name=nomad-apm
2026-03-22T23:04:14.258Z [INFO]  agent.plugin_manager: successfully launched and dispensed plugin: plugin_name=prometheus
2026-03-22T23:04:14.258Z [INFO]  agent.plugin_manager: successfully launched and dispensed plugin: plugin_name=fixed-value
2026-03-22T23:04:14.258Z [INFO]  agent.plugin_manager: successfully launched and dispensed plugin: plugin_name=pass-through
2026-03-22T23:04:14.258Z [INFO]  agent.plugin_manager: successfully launched and dispensed plugin: plugin_name=target-value
2026-03-22T23:04:14.258Z [INFO]  agent.plugin_manager: successfully launched and dispensed plugin: plugin_name=threshold
2026-03-22T23:04:14.258Z [INFO]  agent.plugin_manager: successfully launched and dispensed plugin: plugin_name=nomad-target
2026-03-22T23:04:14.260Z [INFO]  policy_manager: starting policy source: source=nomad
2026-03-22T23:04:14.271Z [ERROR] policy_manager: encountered an error getting the latest version for policy: policyID=8a7f3f1c-068b-8c26-d78d-0c9082ad8aab
  error=
  | 3 errors occurred:
  | \t* policy validation failed
  | \t* empty policy, this policy won't execute any verification or scaling and should have enabled set to false
  | \t* empty checks, this policy won't execute any verification or scaling and should have enabled set to false
  | 
  
2026-03-22T23:04:14.275Z [ERROR] policy_manager: encountered an error getting the latest version for policy: policyID=57fe005f-87a9-8671-eba5-0d66f2efbe68
  error=
  | 3 errors occurred:
  | \t* policy validation failed
  | \t* empty policy, this policy won't execute any verification or scaling and should have enabled set to false
  | \t* empty checks, this policy won't execute any verification or scaling and should have enabled set to false
  | 
  
2026-03-22T23:04:29.320Z [ERROR] policy_manager: encountered an error monitoring policy IDs: error="handler: unable to execute policy ID: 9851171e-7760-4d02-b792-632401bca43b, failed get count from metrics: failed to query source: failed to query source: unsupported query type \"\""
2026-03-22T23:04:44.320Z [ERROR] policy_manager: encountered an error monitoring policy IDs: error="handler: unable to execute policy ID: 9851171e-7760-4d02-b792-632401bca43b, failed get count from metrics: failed to query source: failed to query source: unsupported query type \"\""
2026-03-22T23:04:59.319Z [ERROR] policy_manager: encountered an error monitoring policy IDs: error="handler: unable to execute policy ID: 9851171e-7760-4d02-b792-632401bca43b, failed get count from metrics: failed to query source: failed to query source: unsupported query type \"\""
2026-03-22T23:05:14.320Z [ERROR] policy_manager: encountered an error monitoring policy IDs: error="handler: unable to execute policy ID: 9851171e-7760-4d02-b792-632401bca43b, failed get count from metrics: failed to query source: failed to query source: unsupported query type \"\""

```

```
$ nomad scaling policy info 9851171e-7760-4d02-b792-632401bca43b
ID      = 17a7468d
Enabled = true
Target  = Namespace:default,Job:mirror,Group:mirror
Min     = 1
Max     = 10

Policy:
{
    "check": [
        {
            "fixed-value-check": [
                {
                    "strategy": [
                        {
                            "fixed-value": [
                                {
                                    "value": 2.0
                                }
                            ]
                        }
                    ]
                }
            ]
        }
    ]
}
```

### PR DESCRIPTION
**Pull request by hashi-divyansh**
- Remove APM dependency from fixed-value strategy scaling checks
- We were checking whether the user provided the APM source and query; however, we weren't actually using the query values since the required action was already determined in case of fixed-value.

[Ticket](https://hashicorp.atlassian.net/browse/NMD-1397?atlOrigin=eyJpIjoiYWVhODA1OTM0NTU2NGI3NGIxNTM0N2IwMTE2M2UxMDEiLCJwIjoiaiJ9)

**Testing**
```
job "fixed-value-no-apm-test" {
  datacenters = ["dc1"]
  type = "service"

  group "app" {
    count = 1

    scaling {
      enabled = true
      min     = 1
      max     = 5

      policy {
        cooldown            = "30s"
        evaluation_interval = "10s"

        check "force-count-3" {
          # Now source and query not required in case of fix-value strategies
          # source = "prometheus-not-configured"
          # query  = "this_query_should_be_ignored_for_fixed_value"

          strategy "fixed-value" {
            value = 3
          }
        }
      }
    }

task "sleep" {
  driver = "docker"

  config {
    image   = "busybox:1"
    command = "sleep"
    args    = ["3600"]
  }

  resources {
    cpu    = 50
    memory = 64
  }
}
  }
}
```
**Eairlier:** failed to get APM for strategy fixed-value: apm plugin "prometheus-not-configured" not initialized.
**After this PR fix:**  No error; simply it will scale to 3 instances.

-----------------------------------------------------------------

- [x] If a change needs to be reverted, we will roll out an update to the code within 7 days.

## Changes to Security Controls

Are there any changes to security controls (access controls, encryption, logging) in this pull request? If so, explain.

### CODE REVIEW

File: policy/check_test.go [hunk 1]
```diff
@@ -425,3 +426,34 @@ func TestCheckHandler_runCheckAndCapCount_IgnoredStrategyErrorsContinueEvaluatio
 	must.Eq(t, 1, ml.queryCalls)
 	must.Eq(t, 1, sr.runCalls)
 }
+
+func TestCheckHandler_runCheckAndCapCount_FixedValueSkipsAPMQuery(t *testing.T) {
+	nowFunc = func() time.Time {
+		return time.Time{}
+	}
+
```
Comment (gulducat) [inline policy/check_test.go]: Doesn't look like this is used for anything

```suggestion
```

File: policy/check_test.go [hunk 2]
```diff
@@ -425,3 +426,34 @@ func TestCheckHandler_runCheckAndCapCount_IgnoredStrategyErrorsContinueEvaluatio
...
+		Strategy: &sdk.ScalingPolicyStrategy{
+			Name: plugins.InternalStrategyFixedValue,
+		},
+	})
+
+	action, err := runner.runCheckAndCapCount(context.Background(), 5, newQueryMetricsCache())
+	must.NoError(t, err)
+	must.Eq(t, int64(7), action.Count)
+	must.Eq(t, sdk.ScaleDirectionUp, action.Direction)
+	must.Eq(t, 0, ml.queryCalls)
```
Comment (gulducat) [inline policy/check_test.go]: This 0 queryCalls is the primary thing we care about here, yes?

Comment (gulducat) [reply policy/check_test.go]: I still would like to see more informative messages to aid debugging, because these integer comparisons will present very vague errors like `1 != 0`.

```suggestion
	must.Eq(t, 0, ml.queryCalls, must.Sprint("should not have made any apm queries"))
```

Also I wonder if there'd be any value using `test.Eq` for these, which does a `t.Error` and continues, while `must` does `t.Fatal`. Sometimes it's helpful to see multiple failure conditions at once, rather than e.g. seeing `0 != 7` (for action.Count) without any other info that could potentially highlight the underlying cause.

File: policy/handler.go [hunk 3]
```diff
@@ -228,21 +229,34 @@ func (h *Handler) loadCheckRunners(policy *sdk.ScalingPolicy) ([]checker, error)
...
-		for _, check := range policy.Checks {
+		for i, check := range policy.Checks {
+			if check == nil {
+				return nil, fmt.Errorf("invalid check at index %d: check cannot be nil", i)
+			}
 
-			s, err := h.pm.GetStrategyRunner(check.Strategy.Name)
-			if err != nil {
-				return nil, fmt.Errorf("failed to get strategy %s: %w", check.Strategy.Name, err)
+			if check.Strategy == nil || check.Strategy.Name == "" {
```
Comment (gulducat) [inline policy/handler.go:237]: I suppose these `if == nil`s are mainly defensive? We do want to guard against panics, but I'm curious if a user even has the ability to cause a nil `check`.

**Comment by hashi-divyansh** [comment]
My bad; similar work is done [here](https://github.com/hashicorp/nomad-autoscaler/pull/1262) by Tim. I'm investigating why he made changes to the validation.go file, as I didn't see any validation-related errors during my own testing.

File: CHANGELOG.md [hunk 4]
```diff
@@ -13,6 +13,7 @@ IMPROVEMENTS:
 
 BUG FIXES:
 * policy: Fixed a bug where misconfigured strategy checks could crash the autoscaler instead of following normal `on_error` and `on_check_error` behavior. [[GH-1275](https://github.com/hashicorp/nomad-autoscaler/pull/1275)]
+* policy: Fixed-value strategy checks no longer depend on APM lookup or metric query results, allowing fixed-value scaling to proceed when the configured metrics source is unavailable. [[GH-1281](https://github.com/hashicorp/nomad-autoscaler/pull/1281)]
```
Comment (gulducat) [inline CHANGELOG.md]: > when the configured metrics source is unavailable.

Isn't it more that a metrics source/query is not configured at all? This makes it sound like it would work in a case where the APM source goes down, or something, but it doesn't even really make sense to involve metrics at all for a fixed-value target.

File: policy/check_test.go [hunk 5]
```diff
@@ -425,3 +426,34 @@ func TestCheckHandler_runCheckAndCapCount_IgnoredStrategyErrorsContinueEvaluatio
...
+
+	runner := newCheckRunner(&CheckRunnerConfig{
+		Log:            hclog.NewNullLogger(),
+		StrategyRunner: sr,
+		MetricsGetter:  ml,
+		Policy:         testPolicy,
+	}, &sdk.ScalingPolicyCheck{
+		Name:        "fixed-value-check",
+		Source:      "mock",
+		Query:       "query",
```
Comment (gulducat) [inline policy/check_test.go]: Per my changelog comment, wouldn't it be truer to real-world use if these were empty?

```suggestion
		Source:      "", // explicitly empty
		Query:       "",
```

File: policy/handler_test.go [hunk 6]
```diff
@@ -463,6 +464,39 @@ func TestHandler_Run_PolicyOutsideSchedule_Integration(t *testing.T) {
...
+func TestHandler_applyPolicyState_FixedValueDoesNotRequireAPM(t *testing.T) {
+	fixedValuePolicy := &sdk.ScalingPolicy{
+		ID:                 "fixed-value-policy",
+		Type:               sdk.ScalingPolicyTypeHorizontal,
+		EvaluationInterval: time.Second,
+		Target:             &sdk.ScalingPolicyTarget{Name: "mock-target", Config: map[string]string{}},
+		Checks: []*sdk.ScalingPolicyCheck{
+			{
+				Name:   "check-fixed-value",
+				Source: "missing-apm",
```
Comment (gulducat) [inline policy/handler_test.go]: Same as the other,


```suggestion
				Name:   "check-fixed-value",
				Source: "", // explicitly empty
```

File: CHANGELOG.md (hunk 4 above)
Comment (gulducat) [reply CHANGELOG.md]: It's probably worth updating the docs website to this effect, too.

here: https://developer.hashicorp.com/nomad/tools/autoscaling/policy#check-options

and/or here: https://developer.hashicorp.com/nomad/tools/autoscaling/plugins/strategy/fixed-value

**Review by gulducat — COMMENTED** [review]
Here's some comments for ya. Let me know what you think. :)

File: policy/handler.go (hunk 3 above)
Comment (hashi-divyansh) [reply policy/handler.go:237]: Yes. These are defensive checks. 

- `if check == nil {}` because checks are pointer array []* 
- `check.Strategy == nil` because before accessing name `check.Strategy.Name == ""` better to check the Strategy is not nil.

File: policy/check_test.go (hunk 2 above)
Comment (hashi-divyansh) [reply policy/check_test.go]: `This 0 queryCalls is the primary thing we care about here, yes?`
Yes.

File: policy/check_test.go (hunk 1 above)
Comment (hashi-divyansh) [reply policy/check_test.go]: `nowFunc` is a pkg level variable so here we're overwriting it's value before starting the test logic. In this test case `nowFunc ` will not be in use because `query` will not run (or query not even required at all).

File: policy/check_test.go (hunk 5 above)
Comment (hashi-divyansh) [reply policy/check_test.go]: we can remove it entirely.

File: policy/check_test.go (hunk 1 above)
Comment (tgross) [reply policy/check_test.go]: I realize this package-level variable wasn't added in this PR. But in future work we should try to move that out of the package scope and make it an option for the handler/check. It's only there to support tests, but you can't run tests in parallel if you're modifying package-level variables.

File: CHANGELOG.md (hunk 4 above)
Comment (hashi-divyansh) [reply CHANGELOG.md]: I'll add it here  [PR](https://github.com/hashicorp/web-unified-docs/pull/2272)

File: policy/check_test.go (hunk 5 above)
Comment (gulducat) [reply policy/check_test.go]: In cases like this, I do like to explicitly set the zero value (`""` here), because it communicates the intention of the test to someone reading it. The comments you added do that well enough, so no need to change it again, but comments can sometimes be ambiguous or drift from reality in a way that the code cannot.

**Review by gulducat — APPROVED** [review]
LGTM!
