### PR TITLE
Prevent misconfigured strategy errors from panicking policy evaluation

### LINKED ISSUE #1276: Autoscaler panics with "assignment to entry in nil map" when required strategy parameters are missing
### Nomad Autoscaler version

  Nomad Autoscaler v0.4.10-dev (tested against main at 484e111)

  ### Operating system and Environment details

  macOS Darwin 24.6.0, also reproduced on Linux

  ### Description

  When a scaling policy has a misconfigured strategy (e.g., using upper/lower instead of upper_bound/lower_bound in the threshold strategy), the autoscaler panics and crashes.
   This takes down evaluation of all policies, not just the misconfigured one.

  Two issues contribute to the panic:

  1. Fall-through bug in error handling: getNewCountFromStrategy in policy/check.go has a [default case](https://github.com/hashicorp/nomad-autoscaler/blob/484e111f340da34d74e65de4bdfda54170032ae0/policy/check.go#L117) in its error-handling switch that does not return when on_check_error is not "fail". Execution leaks past the if err != nil block and returns the uninitialized ScalingAction from runStrategy's error path (which has Meta == nil) with a nil error.
  2. No nil guard in CapCount: CapCount in sdk/strategy.go [writes to a.Meta](https://github.com/hashicorp/nomad-autoscaler/blob/484e111f340da34d74e65de4bdfda54170032ae0/sdk/strategy.go#L123) without checking for nil. When it tries to cap Count=0 to the policy's Min, it panics.

 ### Reproduction steps

  1. Run `nomad agent -dev`
  2. Submit the following job:

```hcl
  job "test-scaling-bug" {
    datacenters = ["dc1"]
    type        = "service"

    group "app" {
      count = 1

      scaling {
        enabled = true
        min     = 1
        max     = 5

        policy {
          cooldown            = "30s"
          evaluation_interval = "10s"

          check "cpu_check" {
            source = "nomad-apm"
            query  = "avg_cpu"

            strategy "threshold" {
              # BUG: using "upper"/"lower" instead of "upper_bound"/"lower_bound"
              upper = 80
              lower = 10
            }
          }
        }
      }

      task "sleep" {
        driver = "raw_exec"

        config {
          command = "/bin/sleep"
          args    = ["3600"]
        }

        resources {
          cpu    = 10
          memory = 10
        }
      }
    }
  }
```

  3. Run the autoscaler with the nomad-apm, nomad-target, and threshold plugins
  4. Wait for the evaluation interval to trigger

  **Expected:** The autoscaler logs a warning about the misconfigured strategy and continues evaluating other policies.

  **Actual:** The autoscaler panics and crashes.

  ### Panic output

  Full crash log: https://gist.github.com/ruffin/bcefd012a34e2f7ca8d8c87aad565f23

### PR DESCRIPTION
**Pull request by hashi-divyansh**
This fixes a panic in policy evaluation caused by misconfigured strategy checks.

A strategy execution error on a non-fail path could fall through and return a
zero-value scaling action. That action then flowed into scaling-action mutators,
which made the panic path possible when metadata was nil.

With this change:
- non-fail strategy errors return cleanly through the normal error path
- ignored/default strategy failures no longer leak a zero-value action as a
  successful strategy result
- nil-Meta ScalingAction mutator behavior remains covered by regression tests

[Issue](https://github.com/hashicorp/nomad-autoscaler/issues/1276). [Ticket](https://hashicorp.atlassian.net/browse/NMD-1392?atlOrigin=eyJpIjoiNzJiM2NlYWNjMDhkNDVmMDg1NDZjOTlhZjZmMTc4MDMiLCJwIjoiaiJ9)
----------------------------------------------------------
**Testing**

job file:
```
job "test-scaling-bug-bad" {
  datacenters = ["dc1"]
  type        = "service"

  group "app" {
    count = 1

    scaling {
      enabled = true
      min     = 1
      max     = 5

      policy {
        cooldown            = "30s"
        evaluation_interval = "10s"

        check "cpu_check" {
          source = "nomad-apm"
          query  = "avg_cpu"

          strategy "threshold" {
            # intentionally wrong keys
            upper = 80
            lower = 10
            delta = 1
          }
        }
      }
    }

    task "sleep" {
      driver = "raw_exec"

      config {
        command = "/bin/sleep"
        args    = ["3600"]
      }

      resources {
        cpu    = 10
        memory = 10
      }
    }
  }
}
```
autoscaler-local.hcl 
```

log_level = "TRACE"

nomad {
  address = "http://127.0.0.1:4646"
}

apm "nomad-apm" {
  driver = "nomad-apm"
}

target "nomad-target" {
  driver = "nomad-target"
}

strategy "threshold" {
  driver = "threshold"
}

policy {
  source "nomad" {}
}
```

Logs when build and use autoscaler from the main branch: 

```

divyansh@Divyanshs-MacBook-Pro ~/Desktop/Hashicorp/nomad-autoscaler (main) % ./bin/nomad-autoscaler agent -config=./autoscaler-local.hcl
2026-04-17T22:10:21.226+0530 [INFO]  agent: starting Nomad Autoscaler agent
2026-04-17T22:10:21.226+0530 [INFO]  agent: Nomad Autoscaler agent configuration:
2026-04-17T22:10:21.226+0530 [INFO]  agent
2026-04-17T22:10:21.226+0530 [INFO]  agent:         Bind Addrs: 127.0.0.1
2026-04-17T22:10:21.226+0530 [INFO]  agent:  High Availability: false
2026-04-17T22:10:21.226+0530 [INFO]  agent:          Log Level: TRACE
2026-04-17T22:10:21.226+0530 [INFO]  agent:            Plugins: /Users/divyansh/Desktop/Hashicorp/nomad-autoscaler/plugins
2026-04-17T22:10:21.226+0530 [INFO]  agent:           Policies: 
2026-04-17T22:10:21.226+0530 [INFO]  agent:            Version: v0.4.10-dev (484e111)
2026-04-17T22:10:21.226+0530 [INFO]  agent
2026-04-17T22:10:21.226+0530 [INFO]  agent: Nomad Autoscaler agent started! Log data will stream in below
2026-04-17T22:10:21.227+0530 [INFO]  agent.http_server: server now listening for connections: address=127.0.0.1:8080
2026-04-17T22:10:21.305+0530 [INFO]  agent.plugin_manager: successfully launched and dispensed plugin: plugin_name=nomad-apm
2026-04-17T22:10:21.305+0530 [INFO]  agent.plugin_manager: successfully launched and dispensed plugin: plugin_name=pass-through
2026-04-17T22:10:21.305+0530 [INFO]  agent.plugin_manager: successfully launched and dispensed plugin: plugin_name=target-value
2026-04-17T22:10:21.305+0530 [INFO]  agent.plugin_manager: successfully launched and dispensed plugin: plugin_name=threshold
2026-04-17T22:10:21.305+0530 [INFO]  agent.plugin_manager: successfully launched and dispensed plugin: plugin_name=fixed-value
2026-04-17T22:10:21.336+0530 [INFO]  agent.plugin_manager: successfully launched and dispensed plugin: plugin_name=nomad-target
2026-04-17T22:10:21.336+0530 [INFO]  policy_manager: starting policy source: source=nomad
2026-04-17T22:10:21.336+0530 [TRACE] policy_manager:  starting to monitor policies
2026-04-17T22:10:21.336+0530 [DEBUG] nomad_policy_source: starting policy blocking query watcher
2026-04-17T22:10:21.338+0530 [TRACE] policy_manager: received policy IDs listing: num=2 policy_source=nomad
2026-04-17T22:10:21.339+0530 [TRACE] policy_manager: creating new handler: policy_id=dd09d0cf-965e-85f0-f544-87a020b64932 policy_source=nomad
2026-04-17T22:10:21.339+0530 [DEBUG] policy_manager: creating new policy handler: policy_id="&{dd09d0cf-965e-85f0-f544-87a020b64932 horizontal 0 1 5 true  30s 30s 10s <nil> [0x140003c8080] 0x140005b2330}"
2026-04-17T22:10:21.339+0530 [DEBUG] internal_plugin.nomad-target: starting job status handler: Job=test-scaling-bug
2026-04-17T22:10:21.340+0530 [TRACE] policy_manager.policy_handler: starting policy handler: policy_id=dd09d0cf-965e-85f0-f544-87a020b64932 source=nomad target=nomad-target target_config="map[Group:app Job:test-scaling-bug Namespace:default _nomad_autoscaler_grpc_timeout:7.5s]"
2026-04-17T22:10:21.341+0530 [TRACE] policy_manager: creating new handler: policy_id=c72a114c-5a5f-c098-95d1-704a0211e1a8 policy_source=nomad
2026-04-17T22:10:21.341+0530 [DEBUG] policy_manager: creating new policy handler: policy_id="&{c72a114c-5a5f-c098-95d1-704a0211e1a8 horizontal 0 1 5 true  30s 30s 10s <nil> [0x14000168200] 0x1400064a3a8}"
2026-04-17T22:10:21.341+0530 [DEBUG] internal_plugin.nomad-target: starting job status handler: Job=test-scaling-bug-bad
2026-04-17T22:10:21.342+0530 [TRACE] policy_manager.policy_handler: starting policy handler: policy_id=c72a114c-5a5f-c098-95d1-704a0211e1a8 source=nomad target=nomad-target target_config="map[Group:app Job:test-scaling-bug-bad Namespace:default _nomad_autoscaler_grpc_timeout:7.5s]"
2026-04-17T22:10:31.341+0530 [DEBUG] policy_manager.policy_handler: received policy for evaluation: policy_id=dd09d0cf-965e-85f0-f544-87a020b64932 source=nomad target=nomad-target target_config="map[Group:app Job:test-scaling-bug Namespace:default _nomad_autoscaler_grpc_timeout:7.5s]"
2026-04-17T22:10:31.341+0530 [DEBUG] policy_manager.policy_handler.check_handler: received policy check for evaluation: check=cpu_check policy_id=dd09d0cf-965e-85f0-f544-87a020b64932 source=nomad-apm strategy=threshold target=nomad-target target_config="map[Group:app Job:test-scaling-bug Namespace:default _nomad_autoscaler_grpc_timeout:7.5s]"
2026-04-17T22:10:31.341+0530 [DEBUG] policy_manager.policy_handler.check_handler: querying source: check=cpu_check policy_id=dd09d0cf-965e-85f0-f544-87a020b64932 source=nomad-apm strategy=threshold target=nomad-target target_config="map[Group:app Job:test-scaling-bug Namespace:default _nomad_autoscaler_grpc_timeout:7.5s]" query=taskgroup_avg_cpu/app/test-scaling-bug@default source=nomad-apm
2026-04-17T22:10:31.341+0530 [DEBUG] internal_plugin.nomad-apm: expanded query: from=taskgroup_avg_cpu/app/test-scaling-bug@default to="&plugin.taskGroupQuery{metric:\"cpu\", namespace:\"default\", job:\"test-scaling-bug\", group:\"app\", operation:\"avg\"}"
2026-04-17T22:10:31.342+0530 [DEBUG] policy_manager.policy_handler: received policy for evaluation: policy_id=c72a114c-5a5f-c098-95d1-704a0211e1a8 source=nomad target=nomad-target target_config="map[Group:app Job:test-scaling-bug-bad Namespace:default _nomad_autoscaler_grpc_timeout:7.5s]"
2026-04-17T22:10:31.342+0530 [DEBUG] policy_manager.policy_handler.check_handler: received policy check for evaluation: check=cpu_check policy_id=c72a114c-5a5f-c098-95d1-704a0211e1a8 source=nomad-apm strategy=threshold target=nomad-target target_config="map[Group:app Job:test-scaling-bug-bad Namespace:default _nomad_autoscaler_grpc_timeout:7.5s]"
2026-04-17T22:10:31.342+0530 [DEBUG] policy_manager.policy_handler.check_handler: querying source: check=cpu_check policy_id=c72a114c-5a5f-c098-95d1-704a0211e1a8 source=nomad-apm strategy=threshold target=nomad-target target_config="map[Group:app Job:test-scaling-bug-bad Namespace:default _nomad_autoscaler_grpc_timeout:7.5s]" query=taskgroup_avg_cpu/app/test-scaling-bug-bad@default source=nomad-apm
2026-04-17T22:10:31.342+0530 [DEBUG] internal_plugin.nomad-apm: expanded query: from=taskgroup_avg_cpu/app/test-scaling-bug-bad@default to="&plugin.taskGroupQuery{metric:\"cpu\", namespace:\"default\", job:\"test-scaling-bug-bad\", group:\"app\", operation:\"avg\"}"
2026-04-17T22:10:31.345+0530 [DEBUG] internal_plugin.nomad-apm: metrics found: num_data_points=1 query=taskgroup_avg_cpu/app/test-scaling-bug-bad@default
2026-04-17T22:10:31.346+0530 [DEBUG] policy_manager.policy_handler.check_handler: calculating new count: check=cpu_check policy_id=c72a114c-5a5f-c098-95d1-704a0211e1a8 source=nomad-apm strategy=threshold target=nomad-target target_config="map[Group:app Job:test-scaling-bug-bad Namespace:default _nomad_autoscaler_grpc_timeout:7.5s]" current count=1
2026-04-17T22:10:31.346+0530 [DEBUG] policy_manager.policy_handler.check_handler: running strategy: check=cpu_check policy_id=c72a114c-5a5f-c098-95d1-704a0211e1a8 source=nomad-apm strategy=threshold target=nomad-target target_config="map[Group:app Job:test-scaling-bug-bad Namespace:default _nomad_autoscaler_grpc_timeout:7.5s]" strategy=threshold check=cpu_check
2026-04-17T22:10:31.346+0530 [DEBUG] internal_plugin.nomad-apm: metrics found: num_data_points=1 query=taskgroup_avg_cpu/app/test-scaling-bug@default
2026-04-17T22:10:31.346+0530 [DEBUG] policy_manager.policy_handler.check_handler: calculating new count: check=cpu_check policy_id=dd09d0cf-965e-85f0-f544-87a020b64932 source=nomad-apm strategy=threshold target=nomad-target target_config="map[Group:app Job:test-scaling-bug Namespace:default _nomad_autoscaler_grpc_timeout:7.5s]" current count=1
2026-04-17T22:10:31.346+0530 [DEBUG] policy_manager.policy_handler.check_handler: running strategy: check=cpu_check policy_id=dd09d0cf-965e-85f0-f544-87a020b64932 source=nomad-apm strategy=threshold target=nomad-target target_config="map[Group:app Job:test-scaling-bug Namespace:default _nomad_autoscaler_grpc_timeout:7.5s]" strategy=threshold check=cpu_check
2026-04-17T22:10:31.346+0530 [WARN]  policy_manager.policy_handler.check_handler: failed to run check: check=cpu_check policy_id=dd09d0cf-965e-85f0-f544-87a020b64932 source=nomad-apm strategy=threshold target=nomad-target target_config="map[Group:app Job:test-scaling-bug Namespace:default _nomad_autoscaler_grpc_timeout:7.5s]" check=cpu_check on_error="" on_check_error="" error="failed to execute strategy: missing required field, must have either \"lower_bound\" or \"upper_bound\""
2026-04-17T22:10:31.346+0530 [WARN]  policy_manager.policy_handler.check_handler: failed to run check: check=cpu_check policy_id=c72a114c-5a5f-c098-95d1-704a0211e1a8 source=nomad-apm strategy=threshold target=nomad-target target_config="map[Group:app Job:test-scaling-bug-bad Namespace:default _nomad_autoscaler_grpc_timeout:7.5s]" check=cpu_check on_error="" on_check_error="" error="failed to execute strategy: missing required field, must have either \"lower_bound\" or \"upper_bound\""
panic: assignment to entry in nil map

goroutine 87 [running]:
github.com/hashicorp/nomad-autoscaler/sdk.(*ScalingAction).CapCount(0x14000357a88, 0x1047c1058?, 0x140002a8cd0?)
        /Users/divyansh/Desktop/Hashicorp/nomad-autoscaler/sdk/strategy.go:123 +0x68
github.com/hashicorp/nomad-autoscaler/policy.(*checkRunner).runCheckAndCapCount(0x140000607e0, {0x1047c1058, 0x140002a8cd0}, 0x1, 0x1400014a080)
        /Users/divyansh/Desktop/Hashicorp/nomad-autoscaler/policy/check.go:279 +0x274
github.com/hashicorp/nomad-autoscaler/policy.(*Handler).calculateNewCount(0x140003ca160, {0x1047c1058, 0x140002a8cd0}, 0x1)
        /Users/divyansh/Desktop/Hashicorp/nomad-autoscaler/policy/handler.go:475 +0x20c
github.com/hashicorp/nomad-autoscaler/policy.(*Handler).Run(0x140003ca160, {0x1047c1058, 0x140002a8cd0})
        /Users/divyansh/Desktop/Hashicorp/nomad-autoscaler/policy/handler.go:318 +0x1fc
created by github.com/hashicorp/nomad-autoscaler/policy.(*Manager).processMessageAndUpdateHandlers in goroutine 56
        /Users/divyansh/Desktop/Hashicorp/nomad-autoscaler/policy/manager.go:300 +0x810
```

Logs when build the autoscaler from this branch:
```
divyansh@Divyanshs-MacBook-Pro ~/Desktop/Hashicorp/nomad-autoscaler (b-NMD-1362-guard-scalingAction-mutators-against-nil-meta) % ./bin/nomad-autoscaler agent -config=./autoscaler-local.hcl 
2026-04-17T22:23:45.081+0530 [INFO]  agent: starting Nomad Autoscaler agent
2026-04-17T22:23:45.081+0530 [INFO]  agent: Nomad Autoscaler agent configuration:
2026-04-17T22:23:45.081+0530 [INFO]  agent
2026-04-17T22:23:45.081+0530 [INFO]  agent:         Bind Addrs: 127.0.0.1
2026-04-17T22:23:45.081+0530 [INFO]  agent:  High Availability: false
2026-04-17T22:23:45.081+0530 [INFO]  agent:          Log Level: TRACE
2026-04-17T22:23:45.081+0530 [INFO]  agent:            Plugins: /Users/divyansh/Desktop/Hashicorp/nomad-autoscaler/plugins
2026-04-17T22:23:45.081+0530 [INFO]  agent:           Policies: 
2026-04-17T22:23:45.081+0530 [INFO]  agent:            Version: v0.4.10-dev (3e7d828)
2026-04-17T22:23:45.081+0530 [INFO]  agent
2026-04-17T22:23:45.081+0530 [INFO]  agent: Nomad Autoscaler agent started! Log data will stream in below
2026-04-17T22:23:45.081+0530 [INFO]  agent.http_server: server now listening for connections: address=127.0.0.1:8080
2026-04-17T22:23:45.162+0530 [INFO]  agent.plugin_manager: successfully launched and dispensed plugin: plugin_name=nomad-target
2026-04-17T22:23:45.199+0530 [INFO]  agent.plugin_manager: successfully launched and dispensed plugin: plugin_name=nomad-apm
2026-04-17T22:23:45.199+0530 [INFO]  agent.plugin_manager: successfully launched and dispensed plugin: plugin_name=fixed-value
2026-04-17T22:23:45.199+0530 [INFO]  agent.plugin_manager: successfully launched and dispensed plugin: plugin_name=pass-through
2026-04-17T22:23:45.199+0530 [INFO]  agent.plugin_manager: successfully launched and dispensed plugin: plugin_name=target-value
2026-04-17T22:23:45.199+0530 [INFO]  agent.plugin_manager: successfully launched and dispensed plugin: plugin_name=threshold
2026-04-17T22:23:45.199+0530 [INFO]  policy_manager: starting policy source: source=nomad
2026-04-17T22:23:45.199+0530 [TRACE] policy_manager:  starting to monitor policies
2026-04-17T22:23:45.199+0530 [DEBUG] nomad_policy_source: starting policy blocking query watcher
2026-04-17T22:23:45.201+0530 [TRACE] policy_manager: received policy IDs listing: num=2 policy_source=nomad
2026-04-17T22:23:45.202+0530 [TRACE] policy_manager: creating new handler: policy_id=dd09d0cf-965e-85f0-f544-87a020b64932 policy_source=nomad
2026-04-17T22:23:45.202+0530 [DEBUG] policy_manager: creating new policy handler: policy_id="&{dd09d0cf-965e-85f0-f544-87a020b64932 horizontal 0 1 5 true  30s 30s 10s <nil> [0x14000294080] 0x140006900a8}"
2026-04-17T22:23:45.202+0530 [DEBUG] internal_plugin.nomad-target: starting job status handler: Job=test-scaling-bug
2026-04-17T22:23:45.203+0530 [TRACE] policy_manager.policy_handler: starting policy handler: policy_id=dd09d0cf-965e-85f0-f544-87a020b64932 source=nomad target=nomad-target target_config="map[Group:app Job:test-scaling-bug Namespace:default _nomad_autoscaler_grpc_timeout:7.5s]"
2026-04-17T22:23:45.204+0530 [TRACE] policy_manager: creating new handler: policy_id=c72a114c-5a5f-c098-95d1-704a0211e1a8 policy_source=nomad
2026-04-17T22:23:45.204+0530 [DEBUG] policy_manager: creating new policy handler: policy_id="&{c72a114c-5a5f-c098-95d1-704a0211e1a8 horizontal 0 1 5 true  30s 30s 10s <nil> [0x1400036e400] 0x140003a5938}"
2026-04-17T22:23:45.204+0530 [DEBUG] internal_plugin.nomad-target: starting job status handler: Job=test-scaling-bug-bad
2026-04-17T22:23:45.205+0530 [TRACE] policy_manager.policy_handler: starting policy handler: policy_id=c72a114c-5a5f-c098-95d1-704a0211e1a8 source=nomad target=nomad-target target_config="map[Group:app Job:test-scaling-bug-bad Namespace:default _nomad_autoscaler_grpc_timeout:7.5s]"
2026-04-17T22:23:55.203+0530 [DEBUG] policy_manager.policy_handler: received policy for evaluation: policy_id=dd09d0cf-965e-85f0-f544-87a020b64932 source=nomad target=nomad-target target_config="map[Group:app Job:test-scaling-bug Namespace:default _nomad_autoscaler_grpc_timeout:7.5s]"
2026-04-17T22:23:55.203+0530 [DEBUG] policy_manager.policy_handler.check_handler: received policy check for evaluation: check=cpu_check policy_id=dd09d0cf-965e-85f0-f544-87a020b64932 source=nomad-apm strategy=threshold target=nomad-target target_config="map[Group:app Job:test-scaling-bug Namespace:default _nomad_autoscaler_grpc_timeout:7.5s]"
2026-04-17T22:23:55.203+0530 [DEBUG] policy_manager.policy_handler.check_handler: querying source: check=cpu_check policy_id=dd09d0cf-965e-85f0-f544-87a020b64932 source=nomad-apm strategy=threshold target=nomad-target target_config="map[Group:app Job:test-scaling-bug Namespace:default _nomad_autoscaler_grpc_timeout:7.5s]" query=taskgroup_avg_cpu/app/test-scaling-bug@default source=nomad-apm
2026-04-17T22:23:55.204+0530 [DEBUG] internal_plugin.nomad-apm: expanded query: from=taskgroup_avg_cpu/app/test-scaling-bug@default to="&plugin.taskGroupQuery{metric:\"cpu\", namespace:\"default\", job:\"test-scaling-bug\", group:\"app\", operation:\"avg\"}"
2026-04-17T22:23:55.205+0530 [DEBUG] policy_manager.policy_handler: received policy for evaluation: policy_id=c72a114c-5a5f-c098-95d1-704a0211e1a8 source=nomad target=nomad-target target_config="map[Group:app Job:test-scaling-bug-bad Namespace:default _nomad_autoscaler_grpc_timeout:7.5s]"
2026-04-17T22:23:55.205+0530 [DEBUG] policy_manager.policy_handler.check_handler: received policy check for evaluation: check=cpu_check policy_id=c72a114c-5a5f-c098-95d1-704a0211e1a8 source=nomad-apm strategy=threshold target=nomad-target target_config="map[Group:app Job:test-scaling-bug-bad Namespace:default _nomad_autoscaler_grpc_timeout:7.5s]"
2026-04-17T22:23:55.205+0530 [DEBUG] policy_manager.policy_handler.check_handler: querying source: check=cpu_check policy_id=c72a114c-5a5f-c098-95d1-704a0211e1a8 source=nomad-apm strategy=threshold target=nomad-target target_config="map[Group:app Job:test-scaling-bug-bad Namespace:default _nomad_autoscaler_grpc_timeout:7.5s]" query=taskgroup_avg_cpu/app/test-scaling-bug-bad@default source=nomad-apm
2026-04-17T22:23:55.205+0530 [DEBUG] internal_plugin.nomad-apm: expanded query: from=taskgroup_avg_cpu/app/test-scaling-bug-bad@default to="&plugin.taskGroupQuery{metric:\"cpu\", namespace:\"default\", job:\"test-scaling-bug-bad\", group:\"app\", operation:\"avg\"}"
2026-04-17T22:23:55.216+0530 [DEBUG] internal_plugin.nomad-apm: metrics found: num_data_points=1 query=taskgroup_avg_cpu/app/test-scaling-bug-bad@default
2026-04-17T22:23:55.216+0530 [DEBUG] policy_manager.policy_handler.check_handler: calculating new count: check=cpu_check policy_id=c72a114c-5a5f-c098-95d1-704a0211e1a8 source=nomad-apm strategy=threshold target=nomad-target target_config="map[Group:app Job:test-scaling-bug-bad Namespace:default _nomad_autoscaler_grpc_timeout:7.5s]" current count=1
2026-04-17T22:23:55.216+0530 [DEBUG] policy_manager.policy_handler.check_handler: running strategy: check=cpu_check policy_id=c72a114c-5a5f-c098-95d1-704a0211e1a8 source=nomad-apm strategy=threshold target=nomad-target target_config="map[Group:app Job:test-scaling-bug-bad Namespace:default _nomad_autoscaler_grpc_timeout:7.5s]" strategy=threshold check=cpu_check
2026-04-17T22:23:55.216+0530 [WARN]  policy_manager.policy_handler.check_handler: failed to run check: check=cpu_check policy_id=c72a114c-5a5f-c098-95d1-704a0211e1a8 source=nomad-apm strategy=threshold target=nomad-target target_config="map[Group:app Job:test-scaling-bug-bad Namespace:default _nomad_autoscaler_grpc_timeout:7.5s]" check=cpu_check on_error="" on_check_error="" error="failed to execute strategy: missing required field, must have either \"lower_bound\" or \"upper_bound\""
2026-04-17T22:23:55.216+0530 [DEBUG] policy_manager.policy_handler: check selected: policy_id=c72a114c-5a5f-c098-95d1-704a0211e1a8 source=nomad target=nomad-target target_config="map[Group:app Job:test-scaling-bug-bad Namespace:default _nomad_autoscaler_grpc_timeout:7.5s]" direction=none count=1
2026-04-17T22:23:55.217+0530 [INFO]  policy_manager.policy_handler: calculating scaling target: policy_id=c72a114c-5a5f-c098-95d1-704a0211e1a8 source=nomad target=nomad-target target_config="map[Group:app Job:test-scaling-bug-bad Namespace:default _nomad_autoscaler_grpc_timeout:7.5s]" policy_id=c72a114c-5a5f-c098-95d1-704a0211e1a8 from=1 to=1 reason="capped count from 0 to 1 to stay within limits" meta="map[nomad_autoscaler.count.capped:true nomad_autoscaler.count.original:0 nomad_autoscaler.reason_history:[]]"
2026-04-17T22:23:55.217+0530 [INFO]  policy_manager.policy_handler: skipping scaling, no action needed: policy_id=c72a114c-5a5f-c098-95d1-704a0211e1a8 source=nomad target=nomad-target target_config="map[Group:app Job:test-scaling-bug-bad Namespace:default _nomad_autoscaler_grpc_timeout:7.5s]"
2026-04-17T22:23:55.217+0530 [DEBUG] internal_plugin.nomad-apm: metrics found: num_data_points=1 query=taskgroup_avg_cpu/app/test-scaling-bug@default
2026-04-17T22:23:55.217+0530 [DEBUG] policy_manager.policy_handler.check_handler: calculating new count: check=cpu_check policy_id=dd09d0cf-965e-85f0-f544-87a020b64932 source=nomad-apm strategy=threshold target=nomad-target target_config="map[Group:app Job:test-scaling-bug Namespace:default _nomad_autoscaler_grpc_timeout:7.5s]" current count=1
2026-04-17T22:23:55.217+0530 [DEBUG] policy_manager.policy_handler.check_handler: running strategy: check=cpu_check policy_id=dd09d0cf-965e-85f0-f544-87a020b64932 source=nomad-apm strategy=threshold target=nomad-target target_config="map[Group:app Job:test-scaling-bug Namespace:default _nomad_autoscaler_grpc_timeout:7.5s]" strategy=threshold check=cpu_check
2026-04-17T22:23:55.217+0530 [WARN]  policy_manager.policy_handler.check_handler: failed to run check: check=cpu_check policy_id=dd09d0cf-965e-85f0-f544-87a020b64932 source=nomad-apm strategy=threshold target=nomad-target target_config="map[Group:app Job:test-scaling-bug Namespace:default _nomad_autoscaler_grpc_timeout:7.5s]" check=cpu_check on_error="" on_check_error="" error="failed to execute strategy: missing required field, must have either \"lower_bound\" or \"upper_bound\""
2026-04-17T22:23:55.217+0530 [DEBUG] policy_manager.policy_handler: check selected: policy_id=dd09d0cf-965e-85f0-f544-87a020b64932 source=nomad target=nomad-target target_config="map[Group:app Job:test-scaling-bug Namespace:default _nomad_autoscaler_grpc_timeout:7.5s]" direction=none count=1
2026-04-17T22:23:55.218+0530 [INFO]  policy_manager.policy_handler: calculating scaling target: policy_id=dd09d0cf-965e-85f0-f544-87a020b64932 source=nomad target=nomad-target target_config="map[Group:app Job:test-scaling-bug Namespace:default _nomad_autoscaler_grpc_timeout:7.5s]" policy_id=dd09d0cf-965e-85f0-f544-87a020b64932 from=1 to=1 reason="capped count from 0 to 1 to stay within limits" meta="map[nomad_autoscaler.count.capped:true nomad_autoscaler.count.original:0 nomad_autoscaler.reason_history:[]]"
2026-04-17T22:23:55.218+0530 [INFO]  policy_manager.policy_handler: skipping scaling, no action needed: policy_id=dd09d0cf-965e-85f0-f544-87a020b64932 source=nomad target=nomad-target target_config="map[Group:app Job:test-scaling-bug Namespace:default _nomad_autoscaler_grpc_timeout:7.5s]"
2026-04-17T22:24:05.204+0530 [DEBUG] policy_manager.policy_handler: received policy for evaluation: policy_id=dd09d0cf-965e-85f0-f544-87a020b64932 source=nomad target=nomad-target target_config="map[Group:app Job:test-scaling-bug Namespace:default _nomad_autoscaler_grpc_timeout:7.5s]"
2026-04-17T22:24:05.204+0530 [DEBUG] policy_manager.policy_handler.check_handler: received policy check for evaluation: check=cpu_check policy_id=dd09d0cf-965e-85f0-f544-87a020b64932 source=nomad-apm strategy=threshold target=nomad-target target_config="map[Group:app Job:test-scaling-bug Namespace:default _nomad_autoscaler_grpc_timeout:7.5s]"
2026-04-17T22:24:05.204+0530 [DEBUG] policy_manager.policy_handler.check_handler: querying source: check=cpu_check policy_id=dd09d0cf-965e-85f0-f544-87a020b64932 source=nomad-apm strategy=threshold target=nomad-target target_config="map[Group:app Job:test-scaling-bug Namespace:default _nomad_autoscaler_grpc_timeout:7.5s]" query=taskgroup_avg_cpu/app/test-scaling-bug@default source=nomad-apm
2026-04-17T22:24:05.204+0530 [DEBUG] internal_plugin.nomad-apm: expanded query: from=taskgroup_avg_cpu/app/test-scaling-bug@default to="&plugin.taskGroupQuery{metric:\"cpu\", namespace:\"default\", job:\"test-scaling-bug\", group:\"app\", operation:\"avg\"}"
2026-04-17T22:24:05.205+0530 [DEBUG] policy_manager.policy_handler: received policy for evaluation: policy_id=c72a114c-5a5f-c098-95d1-704a0211e1a8 source=nomad target=nomad-target target_config="map[Group:app Job:test-scaling-bug-bad Namespace:default _nomad_autoscaler_grpc_timeout:7.5s]"
2026-04-17T22:24:05.205+0530 [DEBUG] policy_manager.policy_handler.check_handler: received policy check for evaluation: check=cpu_check policy_id=c72a114c-5a5f-c098-95d1-704a0211e1a8 source=nomad-apm strategy=threshold target=nomad-target target_config="map[Group:app Job:test-scaling-bug-bad Namespace:default _nomad_autoscaler_grpc_timeout:7.5s]"
2026-04-17T22:24:05.205+0530 [DEBUG] policy_manager.policy_handler.check_handler: querying source: check=cpu_check policy_id=c72a114c-5a5f-c098-95d1-704a0211e1a8 source=nomad-apm strategy=threshold target=nomad-target target_config="map[Group:app Job:test-scaling-bug-bad Namespace:default _nomad_autoscaler_grpc_timeout:7.5s]" query=taskgroup_avg_cpu/app/test-scaling-bug-bad@default source=nomad-apm
2026-04-17T22:24:05.205+0530 [DEBUG] internal_plugin.nomad-apm: expanded query: from=taskgroup_avg_cpu/app/test-scaling-bug-bad@default to="&plugin.taskGroupQuery{metric:\"cpu\", namespace:\"default\", job:\"test-scaling-bug-bad\", group:\"app\", operation:\"avg\"}"
2026-04-17T22:24:05.208+0530 [DEBUG] internal_plugin.nomad-apm: metrics found: num_data_points=1 query=taskgroup_avg_cpu/app/test-scaling-bug@default
2026-04-17T22:24:05.209+0530 [DEBUG] policy_manager.policy_handler.check_handler: calculating new count: check=cpu_check policy_id=dd09d0cf-965e-85f0-f544-87a020b64932 source=nomad-apm strategy=threshold target=nomad-target target_config="map[Group:app Job:test-scaling-bug Namespace:default _nomad_autoscaler_grpc_timeout:7.5s]" current count=1
2026-04-17T22:24:05.209+0530 [DEBUG] policy_manager.policy_handler.check_handler: running strategy: check=cpu_check policy_id=dd09d0cf-965e-85f0-f544-87a020b64932 source=nomad-apm strategy=threshold target=nomad-target target_config="map[Group:app Job:test-scaling-bug Namespace:default _nomad_autoscaler_grpc_timeout:7.5s]" strategy=threshold check=cpu_check
2026-04-17T22:24:05.209+0530 [DEBUG] internal_plugin.nomad-apm: metrics found: num_data_points=1 query=taskgroup_avg_cpu/app/test-scaling-bug-bad@default
2026-04-17T22:24:05.209+0530 [DEBUG] policy_manager.policy_handler.check_handler: calculating new count: check=cpu_check policy_id=c72a114c-5a5f-c098-95d1-704a0211e1a8 source=nomad-apm strategy=threshold target=nomad-target target_config="map[Group:app Job:test-scaling-bug-bad Namespace:default _nomad_autoscaler_grpc_timeout:7.5s]" current count=1
2026-04-17T22:24:05.209+0530 [DEBUG] policy_manager.policy_handler.check_handler: running strategy: check=cpu_check policy_id=c72a114c-5a5f-c098-95d1-704a0211e1a8 source=nomad-apm strategy=threshold target=nomad-target target_config="map[Group:app Job:test-scaling-bug-bad Namespace:default _nomad_autoscaler_grpc_timeout:7.5s]" strategy=threshold check=cpu_check
2026-04-17T22:24:05.209+0530 [WARN]  policy_manager.policy_handler.check_handler: failed to run check: check=cpu_check policy_id=dd09d0cf-965e-85f0-f544-87a020b64932 source=nomad-apm strategy=threshold target=nomad-target target_config="map[Group:app Job:test-scaling-bug Namespace:default _nomad_autoscaler_grpc_timeout:7.5s]" check=cpu_check on_error="" on_check_error="" error="failed to execute strategy: missing required field, must have either \"lower_bound\" or \"upper_bound\""
2026-04-17T22:24:05.210+0530 [DEBUG] policy_manager.policy_handler: check selected: policy_id=dd09d0cf-965e-85f0-f544-87a020b64932 source=nomad target=nomad-target target_config="map[Group:app Job:test-scaling-bug Namespace:default _nomad_autoscaler_grpc_timeout:7.5s]" direction=none count=1
2026-04-17T22:24:05.210+0530 [INFO]  policy_manager.policy_handler: calculating scaling target: policy_id=dd09d0cf-965e-85f0-f544-87a020b64932 source=nomad target=nomad-target target_config="map[Group:app Job:test-scaling-bug Namespace:default _nomad_autoscaler_grpc_timeout:7.5s]" policy_id=dd09d0cf-965e-85f0-f544-87a020b64932 from=1 to=1 reason="capped count from 0 to 1 to stay within limits" meta="map[nomad_autoscaler.count.capped:true nomad_autoscaler.count.original:0 nomad_autoscaler.reason_history:[]]"
2026-04-17T22:24:05.210+0530 [INFO]  policy_manager.policy_handler: skipping scaling, no action needed: policy_id=dd09d0cf-965e-85f0-f544-87a020b64932 source=nomad target=nomad-target target_config="map[Group:app Job:test-scaling-bug Namespace:default _nomad_autoscaler_grpc_timeout:7.5s]"
2026-04-17T22:24:05.210+0530 [WARN]  policy_manager.policy_handler.check_handler: failed to run check: check=cpu_check policy_id=c72a114c-5a5f-c098-95d1-704a0211e1a8 source=nomad-apm strategy=threshold target=nomad-target target_config="map[Group:app Job:test-scaling-bug-bad Namespace:default _nomad_autoscaler_grpc_timeout:7.5s]" check=cpu_check on_error="" on_check_error="" error="failed to execute strategy: missing required field, must have either \"lower_bound\" or \"upper_bound\""
2026-04-17T22:24:05.210+0530 [DEBUG] policy_manager.policy_handler: check selected: policy_id=c72a114c-5a5f-c098-95d1-704a0211e1a8 source=nomad target=nomad-target target_config="map[Group:app Job:test-scaling-bug-bad Namespace:default _nomad_autoscaler_grpc_timeout:7.5s]" direction=none count=1
2026-04-17T22:24:05.210+0530 [INFO]  policy_manager.policy_handler: calculating scaling target: policy_id=c72a114c-5a5f-c098-95d1-704a0211e1a8 source=nomad target=nomad-target target_config="map[Group:app Job:test-scaling-bug-bad Namespace:default _nomad_autoscaler_grpc_timeout:7.5s]" policy_id=c72a114c-5a5f-c098-95d1-704a0211e1a8 from=1 to=1 reason="capped count from 0 to 1 to stay within limits" meta="map[nomad_autoscaler.count.capped:true nomad_autoscaler.count.original:0 nomad_autoscaler.reason_history:[]]"
2026-04-17T22:24:05.210+0530 [INFO]  policy_manager.policy_handler: skipping scaling, no action needed: policy_id=c72a114c-5a5f-c098-95d1-704a0211e1a8 source=nomad target=nomad-target target_config="map[Group:app Job:test-scaling-bug-bad Namespace:default _nomad_autoscaler_grpc_timeout:7.5s]"
2026-04-17T22:24:15.204+0530 [DEBUG] policy_manager.policy_handler: received policy for evaluation: policy_id=dd09d0cf-965e-85f0-f544-87a020b64932 source=nomad target=nomad-target target_config="map[Group:app Job:test-scaling-bug Namespace:default _nomad_autoscaler_grpc_timeout:7.5s]"
2026-04-17T22:24:15.204+0530 [DEBUG] policy_manager.policy_handler.check_handler: received policy check for evaluation: check=cpu_check policy_id=dd09d0cf-965e-85f0-f544-87a020b64932 source=nomad-apm strategy=threshold target=nomad-target target_config="map[Group:app Job:test-scaling-bug Namespace:default _nomad_autoscaler_grpc_timeout:7.5s]"
2026-04-17T22:24:15.204+0530 [DEBUG] policy_manager.policy_handler.check_handler: querying source: check=cpu_check policy_id=dd09d0cf-965e-85f0-f544-87a020b64932 source=nomad-apm strategy=threshold target=nomad-target target_config="map[Group:app Job:test-scaling-bug Namespace:default _nomad_autoscaler_grpc_timeout:7.5s]" query=taskgroup_avg_cpu/app/test-scaling-bug@default source=nomad-apm
2026-04-17T22:24:15.204+0530 [DEBUG] internal_plugin.nomad-apm: expanded query: from=taskgroup_avg_cpu/app/test-scaling-bug@default to="&plugin.taskGroupQuery{metric:\"cpu\", namespace:\"default\", job:\"test-scaling-bug\", group:\"app\", operation:\"avg\"}"
2026-04-17T22:24:15.205+0530 [DEBUG] policy_manager.policy_handler: received policy for evaluation: policy_id=c72a114c-5a5f-c098-95d1-704a0211e1a8 source=nomad target=nomad-target target_config="map[Group:app Job:test-scaling-bug-bad Namespace:default _nomad_autoscaler_grpc_timeout:7.5s]"
2026-04-17T22:24:15.205+0530 [DEBUG] policy_manager.policy_handler.check_handler: received policy check for evaluation: check=cpu_check policy_id=c72a114c-5a5f-c098-95d1-704a0211e1a8 source=nomad-apm strategy=threshold target=nomad-target target_config="map[Group:app Job:test-scaling-bug-bad Namespace:default _nomad_autoscaler_grpc_timeout:7.5s]"
2026-04-17T22:24:15.205+0530 [DEBUG] policy_manager.policy_handler.check_handler: querying source: check=cpu_check policy_id=c72a114c-5a5f-c098-95d1-704a0211e1a8 source=nomad-apm strategy=threshold target=nomad-target target_config="map[Group:app Job:test-scaling-bug-bad Namespace:default _nomad_autoscaler_grpc_timeout:7.5s]" query=taskgroup_avg_cpu/app/test-scaling-bug-bad@default source=nomad-apm
2026-04-17T22:24:15.205+0530 [DEBUG] internal_plugin.nomad-apm: expanded query: from=taskgroup_avg_cpu/app/test-scaling-bug-bad@default to="&plugin.taskGroupQuery{metric:\"cpu\", namespace:\"default\", job:\"test-scaling-bug-bad\", group:\"app\", operation:\"avg\"}"
2026-04-17T22:24:15.213+0530 [DEBUG] internal_plugin.nomad-apm: metrics found: num_data_points=1 query=taskgroup_avg_cpu/app/test-scaling-bug@default
2026-04-17T22:24:15.213+0530 [DEBUG] policy_manager.policy_handler.check_handler: calculating new count: check=cpu_check policy_id=dd09d0cf-965e-85f0-f544-87a020b64932 source=nomad-apm strategy=threshold target=nomad-target target_config="map[Group:app Job:test-scaling-bug Namespace:default _nomad_autoscaler_grpc_timeout:7.5s]" current count=1
2026-04-17T22:24:15.213+0530 [DEBUG] policy_manager.policy_handler.check_handler: running strategy: check=cpu_check policy_id=dd09d0cf-965e-85f0-f544-87a020b64932 source=nomad-apm strategy=threshold target=nomad-target target_config="map[Group:app Job:test-scaling-bug Namespace:default _nomad_autoscaler_grpc_timeout:7.5s]" strategy=threshold check=cpu_check
2026-04-17T22:24:15.214+0530 [WARN]  policy_manager.policy_handler.check_handler: failed to run check: check=cpu_check policy_id=dd09d0cf-965e-85f0-f544-87a020b64932 source=nomad-apm strategy=threshold target=nomad-target target_config="map[Group:app Job:test-scaling-bug Namespace:default _nomad_autoscaler_grpc_timeout:7.5s]" check=cpu_check on_error="" on_check_error="" error="failed to execute strategy: missing required field, must have either \"lower_bound\" or \"upper_bound\""
2026-04-17T22:24:15.214+0530 [DEBUG] policy_manager.policy_handler: check selected: policy_id=dd09d0cf-965e-85f0-f544-87a020b64932 source=nomad target=nomad-target target_config="map[Group:app Job:test-scaling-bug Namespace:default _nomad_autoscaler_grpc_timeout:7.5s]" direction=none count=1
2026-04-17T22:24:15.214+0530 [INFO]  policy_manager.policy_handler: calculating scaling target: policy_id=dd09d0cf-965e-85f0-f544-87a020b64932 source=nomad target=nomad-target target_config="map[Group:app Job:test-scaling-bug Namespace:default _nomad_autoscaler_grpc_timeout:7.5s]" policy_id=dd09d0cf-965e-85f0-f544-87a020b64932 from=1 to=1 reason="capped count from 0 to 1 to stay within limits" meta="map[nomad_autoscaler.count.capped:true nomad_autoscaler.count.original:0 nomad_autoscaler.reason_history:[]]"
2026-04-17T22:24:15.214+0530 [INFO]  policy_manager.policy_handler: skipping scaling, no action needed: policy_id=dd09d0cf-965e-85f0-f544-87a020b64932 source=nomad target=nomad-target target_config="map[Group:app Job:test-scaling-bug Namespace:default _nomad_autoscaler_grpc_timeout:7.5s]"
2026-04-17T22:24:15.214+0530 [DEBUG] internal_plugin.nomad-apm: metrics found: num_data_points=1 query=taskgroup_avg_cpu/app/test-scaling-bug-bad@default
2026-04-17T22:24:15.214+0530 [DEBUG] policy_manager.policy_handler.check_handler: calculating new count: check=cpu_check policy_id=c72a114c-5a5f-c098-95d1-704a0211e1a8 source=nomad-apm strategy=threshold target=nomad-target target_config="map[Group:app Job:test-scaling-bug-bad Namespace:default _nomad_autoscaler_grpc_timeout:7.5s]" current count=1
2026-04-17T22:24:15.214+0530 [DEBUG] policy_manager.policy_handler.check_handler: running strategy: check=cpu_check policy_id=c72a114c-5a5f-c098-95d1-704a0211e1a8 source=nomad-apm strategy=threshold target=nomad-target target_config="map[Group:app Job:test-scaling-bug-bad Namespace:default _nomad_autoscaler_grpc_timeout:7.5s]" strategy=threshold check=cpu_check
2026-04-17T22:24:15.214+0530 [WARN]  policy_manager.policy_handler.check_handler: failed to run check: check=cpu_check policy_id=c72a114c-5a5f-c098-95d1-704a0211e1a8 source=nomad-apm strategy=threshold target=nomad-target target_config="map[Group:app Job:test-scaling-bug-bad Namespace:default _nomad_autoscaler_grpc_timeout:7.5s]" check=cpu_check on_error="" on_check_error="" error="failed to execute strategy: missing required field, must have either \"lower_bound\" or \"upper_bound\""
2026-04-17T22:24:15.214+0530 [DEBUG] policy_manager.policy_handler: check selected: policy_id=c72a114c-5a5f-c098-95d1-704a0211e1a8 source=nomad target=nomad-target target_config="map[Group:app Job:test-scaling-bug-bad Namespace:default _nomad_autoscaler_grpc_timeout:7.5s]" direction=none count=1
2026-04-17T22:24:15.214+0530 [INFO]  policy_manager.policy_handler: calculating scaling target: policy_id=c72a114c-5a5f-c098-95d1-704a0211e1a8 source=nomad target=nomad-target target_config="map[Group:app Job:test-scaling-bug-bad Namespace:default _nomad_autoscaler_grpc_timeout:7.5s]" policy_id=c72a114c-5a5f-c098-95d1-704a0211e1a8 from=1 to=1 reason="capped count from 0 to 1 to stay within limits" meta="map[nomad_autoscaler.count.capped:true nomad_autoscaler.count.original:0 nomad_autoscaler.reason_history:[]]"
2026-04-17T22:24:15.214+0530 [INFO]  policy_manager.policy_handler: skipping scaling, no action needed: policy_id=c72a114c-5a5f-c098-95d1-704a0211e1a8 source=nomad target=nomad-target target_config="map[Group:app Job:test-scaling-bug-bad Namespace:default _nomad_autoscaler_grpc_timeout:7.5s]"
```

- [x] If a change needs to be reverted, we will roll out an update to the code within 7 days.

## Changes to Security Controls

Are there any changes to security controls (access controls, encryption, logging) in this pull request? If so, explain.

### CODE REVIEW

File: sdk/strategy.go [hunk 1]
```diff
@@ -90,15 +90,22 @@ func (d ScaleDirection) String() string {
 
 // Canonicalize ensures Action has proper default values.
 func (a *ScalingAction) Canonicalize() {
+	a.ensureMeta()
+}
+
+// ensureMeta initializes the Meta map if it is nil and returns it.
+func (a *ScalingAction) ensureMeta() map[string]interface{} {
```
Comment (hashi-divyansh) [inline sdk/strategy.go:98]: I moved the map initialization logic from the public `Canonicalize()` method to a private `ensureMeta() `method. This is to avoid calling a public method multiple times from within its own package.

Comment (gulducat) [reply sdk/strategy.go]: I don't see anything capturing the return value of this func, so why return it?

I see the reasoning here, since this struct is bare-initialized all over the place with `&sdk.ScalingAction{}` instead of a `NewScalingAction()` constructor func, which are often used to set up maps like this. I don't love the `Canonicalize` pattern, unless it's doing some useful work beyond just initializing things, for this very reason. Personally, I would prefer a `NewScalingAction`, but it may be annoying/dangerous to track down all the callsites that would need it...?

But sprinkling this `ensureMeta` method around, only loosely coupled to the map assignments, feels like it could be missed in the future, as `Canonicalize` apparently was, somewhere, otherwise we wouldn't feel that this is necessary.

Another option would be to make a setter that handles this safely, e.g.

```go
func (a *ScalingAction) setMeta(key string, val any) {
	if a.Meta == nil {
		a.Meta = make(map[string]any)
	}
	a.Meta[key] = val
}
```

and elsewhere, `a.setMeta(strategyActionMetaKeyDryRun, true)`, etc.

That being a private method would not help other packages, if they try to assign to a nil `Meta` themselves, but it would make this struct's methods internally safe, which I believe is the goal of this `ensureMeta` method.

File: policy/check.go [hunk 2]
```diff
@@ -118,6 +117,10 @@ func (ch *checkRunner) getNewCountFromStrategy(ctx context.Context, currentCount
 			if ch.policy.OnCheckError == sdk.ScalingPolicyOnErrorFail {
 				return sdk.ScalingAction{}, err
 			}
+
+			// Non-fatal fallback path: skip this check result and continue evaluating
+			// the remaining checks in the policy.
+			return sdk.ScalingAction{}, nil
```
Comment (gulducat) [inline policy/check.go:123]: Just noting that this is the primary fix, yes?

File: sdk/strategy.go (hunk 1 above)
Comment (gulducat) [reply sdk/strategy.go]: Also, I suppose the fix in `getNewCountFromStrategy` resulted in a subsequent nil panic, which drew your attention here?

File: policy/check.go (hunk 2 above)
Comment (hashi-divyansh) [reply policy/check.go:123]: Yes. This is the main issue 😀

File: sdk/strategy.go (hunk 1 above)
Comment (hashi-divyansh) [reply sdk/strategy.go]: ~~I like the `constructor pattern.` I know it will be a lot of refactoring, but I'll spend some time exploring this option. Also, all the fields in the `ScalingAction struct` are currently exported; I'll see if we can make them unexported.~~

Comment (hashi-divyansh) [reply sdk/strategy.go]: I explored the codebase and found it’s very difficult to completely remove the Canonicalize() pattern. It is highly coupled and used throughout the codebase.

I think the bigger issue here is the exported Meta field; anyone can access it directly and trigger a panic 🤷🏻‍♂️.

File: sdk/strategy.go [hunk 3]
```diff
@@ -112,6 +121,8 @@ func (a *ScalingAction) CapCount(min, max int64) {
 		return
 	}
 
+	a.Canonicalize()
+
```
Comment (gulducat) [inline sdk/strategy.go:125]: This is no longer needed with `setMeta` being used below.

**Review by gulducat — APPROVED** [review]
LGTM!
