### PR TITLE
Re-connect to Nomad if connection is lost

### LINKED ISSUE #119: Autoscaler fails to re-connect to Nomad cluster
When the Autoscaler loses connection to the Nomad cluster, all policy handlers are stopped and are never re-evaluated, even when the Nomad cluster comes back up.

### PR DESCRIPTION
**Pull request by lgfa29**
This PR fixes an issue where the Autoscaler would fail to re-connect to the Nomad server if the connection was dropped.

The main cause for this issue is that the `policyIDsErrCh` was not being consumed, and so the goroutine monitoring the list of policy IDs would block in case of an error.

I also uncovered some more subtle ways that the Autoscaler could fail to re-connect properly:
* policy handlers would exit in case of connection error and never be re-created.
* the policy list ID monitor would silently `continue` if the Autoscler re-connected to a Nomad cluster where the list of policies were different but the modify index had the same value.

To fix these problems I made a few assumptions:
* Policy handlers only exit when their context is closed. They will keep looping even if an error occurs.
* The policy manager is responsible for stopping handlers in case of an [unrecoverable errors](https://github.com/hashicorp/nomad-autoscaler/pull/134/files#diff-bbdb50489b1a80cb45d42cf486e5870bR184-R193).
* The policy manager will re-run if it exists until its context is closed.

Closes #119

### CODE REVIEW

File: policy/nomad/source.go [hunk 1]
```diff
@@ -94,12 +94,6 @@ func (s *Source) MonitorIDs(ctx context.Context, resultCh chan<- []policy.Policy
 				continue
 			}
 
-			// If the index has not changed, the query returned because the timeout
-			// was reached, therefore start the next query loop.
-			if !blocking.IndexHasChanged(meta.LastIndex, q.WaitIndex) {
```
Comment (jrasell) [inline policy/nomad/source.go:99]: > the policy list ID monitor would silently continue if the Autoscler re-connected to a Nomad cluster where the list of policies were different but the modify index had the same value.

I guess this removal relates to the above PR mention. If not please ignore this comment. In what situation would we reconnect to a cluster that has an altered list output but the table index has not changed?

File: policy/manager.go [hunk 2]
```diff
@@ -149,3 +180,23 @@ func (m *Manager) EnforceCooldown(id string, t time.Duration) {
...
+//
+// An error is considered unrecoverable if it has the potential to affect the
+// policy manager's internal state, and so the policy manager should re-run.
+//
+// Example of an unrecoverable error: the Nomad server becomes unreachable;
+// upon reconnecting, the state of the Nomad cluster could be different from
+// what's stored in the policy manager (e.g., a different cluster becomes
+// available in the same address).
+func isUnrecoverableError(err error) bool {
+	unrecoverableErrors := []string{"connection refused", "EOF"}
```
Comment (jrasell) [inline policy/manager.go:195]: The net stdlib package has [custom errors](https://github.com/golang/go/blob/4ec4a792f6e60c9c4f40a928650c66419ee0e446/src/net/net.go#L392) which have a `Temporary()` function. I am not sure this would cover the cases you have specifically found, but something worth noting at least.

File: policy/handler.go [hunk 3]
```diff
@@ -102,7 +102,14 @@ func (h *Handler) Run(ctx context.Context, evalCh chan<- *Evaluation) {
 			return
 		case <-h.doneCh:
 			return
+
 		case err := <-h.errCh:
+			// In case of error, log the error message and loop around.
+			// Handlers never stop running unless ctx.Done() or doneCh is
+			// closed.
+
+			// multierror.Error objects are logged differently to allow for a
```
Comment (jrasell) [inline policy/handler.go:111]: if we have to do this somewhere else in the future, we should certainly pull the logic into a helper.

File: policy/nomad/source.go (hunk 1 above)
Comment (lgfa29) [reply policy/nomad/source.go:99]: It's an odd case that is very unlikely to happen in production, but if you run a Nomad agent in dev mode, register a job with a scaling policy, then stop the dev agent and register the same job again, you will end up with the same index (since the same modifications were executed) but a different list (the policy ID will be different).

The root of this issue is that lists don't have an ID, so you can't really match an index to a list like, for example, a policy. The only way to make sure we have the same list is by iterating over the policy IDs, which we would anyway in the policy handler.

_But_ this is a very unusual case that is extremely unlikely to happen in a real environment. Also, this was an early "fix". Re-running the policy manager on disconnect actually re-creates this monitoring goroutine, so this problem doesn't happen anymore.

I will add this check back since it's useful to avoid unnecessary work.

File: policy/manager.go (hunk 2 above)
Comment (lgfa29) [reply policy/manager.go:195]: TIL

But the problem is when the error reaches the policy manager it has been transformed into a generic `error`. We could start considering using [`error.Wrap`](https://godoc.org/github.com/pkg/errors#Wrap) instead of creating new error objects

File: policy/handler.go (hunk 3 above)
Comment (lgfa29) [reply policy/handler.go:111]: Yeah, it might be worth to even add this to `hclog`. I will keep it here for now since policy validation is the only place we use `multierror` so far.
