### PR TITLE
scaleutils: fix least busy selector on clusters older than v1.0.0

### LINKED ISSUE #506: aws-asg target: Panic while scaling in nodes
Using nomad-autoscaler v0.3.3 OSS, we get the following panic (logs retrieved from our datadog logs, which _may_ be out of order in case the ordering looks funny):

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xd38732]
goroutine 90 [running]:
github.com/hashicorp/nomad-autoscaler/sdk/helper/scaleutils/nodeselector.computeNodeTotalResources(...)
/home/circleci/project/project/sdk/helper/scaleutils/nodeselector/least_busy.go:130
github.com/hashicorp/nomad-autoscaler/sdk/helper/scaleutils/nodeselector.(*leastBusyClusterScaleInNodeSelector).computeNodeResources(0xc000c4e348, 0xc000b1e540, 0x8, 0xc000b34300, 0xc000646270)
/home/circleci/project/project/sdk/helper/scaleutils/nodeselector/least_busy.go:87 +0x112
github.com/hashicorp/nomad-autoscaler/sdk/helper/scaleutils/nodeselector.(*leastBusyClusterScaleInNodeSelector).Select(0xc000c4e348, 0xc000b342c0, 0x8, 0x8, 0x1, 0x2, 0x0, 0x0)
/home/circleci/project/project/sdk/helper/scaleutils/nodeselector/least_busy.go:55 +0xaa
github.com/hashicorp/nomad-autoscaler/sdk/helper/scaleutils.(*ClusterScaleUtils).IdentifyScaleInNodes(0xc0005f6f00, 0xc000e78450, 0x1, 0x40db9b, 0xc000bf9310, 0x8, 0x8, 0x17e8320)
/home/circleci/project/project/sdk/helper/scaleutils/cluster.go:140 +0x5f8
github.com/hashicorp/nomad-autoscaler/plugins/builtin/target/aws-asg/plugin.(*TargetPlugin).scaleIn(0xc0006462a0, 0x1cd04c8, 0xc00003c090, 0xc000cee160, 0x1, 0xc000e78450, 0x0, 0x0)
/home/circleci/project/project/plugins/builtin/target/aws-asg/plugin/aws.go:106 +0x6c
github.com/hashicorp/nomad-autoscaler/plugins/builtin/target/aws-asg/plugin.(*TargetPlugin).Scale(0xc0006462a0, 0x7, 0xc000118780, 0x27, 0xff00, 0xc0010f0630, 0xc000e78450, 0x7f74047277a8, 0xc0012cbc08)
/home/circleci/project/project/plugins/builtin/target/aws-asg/plugin/plugin.go:125 +0x399
github.com/hashicorp/nomad-autoscaler/policyeval.(*BaseWorker).runTargetScale(0xc00008d9f0, 0x7f740472d010, 0xc0006462a0, 0xc000544770, 0x7, 0xc000118780, 0x27, 0xff00, 0xc0010f0630, 0x0, ...)
/home/circleci/project/project/policyeval/base_worker.go:249 +0x23c
github.com/hashicorp/nomad-autoscaler/policyeval.(*BaseWorker).handlePolicy(0xc00008d9f0, 0x1cd0490, 0xc000284bc0, 0xc000a8c050, 0x0, 0x0)
/home/circleci/project/project/policyeval/base_worker.go:215 +0xf4d
github.com/hashicorp/nomad-autoscaler/policyeval.(*BaseWorker).Run(0xc00008d9f0, 0x1cd0490, 0xc000284bc0)
/home/circleci/project/project/policyeval/base_worker.go:76 +0x2d9
created by github.com/hashicorp/nomad-autoscaler/agent.(*Agent).initWorkers
/home/circleci/project/project/agent/agent.go:130 +0x42e
2021/07/01 03:00:07.983048 [ERR] (cli) child process died with exit code 2
```

Running against Nomad 0.12.11+ent.

Happy to provide any extra details that might be useful for debugging.

### PR DESCRIPTION
**Pull request by jrasell**
This adds additional API calls when performing the least busy node
selector as a best effort to work on cluster that running Nomad
versions before v1.0.0.

v1.0.0 including API functionality which allows node resources to
be include in the stub list node object which is used when
performing least busy calculations. In version prior to this, the
information is only available within the node info object.

closes #506

### CODE REVIEW

**Comment by josegonzalez** [comment]
@jrasell if there is a version of this built, we're happy to test it out to see if it gets rid of the reported panics :)

**Review by lgfa29 — APPROVED** [review]
LGTM. Reproduced and test on Nomad v0.12.12.

File: sdk/helper/scaleutils/nodeselector/least_busy.go [hunk 1]
```diff
@@ -48,6 +48,30 @@ func (l *leastBusyClusterScaleInNodeSelector) Select(nodes []*api.NodeListStub,
...
+			}
+			if nodeInfo.NodeResources == nil {
+				l.log.Error("node object does not contain resource info", "node_id", node.ID)
+				return nil
+			}
+
+			// Update the node to include the resource object.
+			node.NodeResources = nodeInfo.NodeResources
+
+			if node.NodeResources == nil && nodeInfo.ReservedResources != nil {
```
Comment (lgfa29) [inline sdk/helper/scaleutils/nodeselector/least_busy.go:70]:
```suggestion
			if node.ReservedResources == nil && nodeInfo.ReservedResources != nil {
```

**Comment by lgfa29** [comment]
> @jrasell if there is a version of this built, we're happy to test it out to see if it gets rid of the reported panics :)

This fix will be available tomorrow when the [nightly](https://github.com/hashicorp/nomad-autoscaler/releases/tag/nightly) release runs.
