### PR TITLE
plugin/apm/nomad: fix spelling mistake in log lines.

### LINKED ISSUE #653: Typo founds
Hi,

I found this typos:

alloacted --> allocated

https://github.com/hashicorp/nomad-autoscaler/blob/12f053eb8b208f83c050685fbf0ac843f55bd51e/plugins/builtin/apm/nomad/plugin/job.go#L82

https://github.com/hashicorp/nomad-autoscaler/blob/12f053eb8b208f83c050685fbf0ac843f55bd51e/plugins/builtin/apm/nomad/plugin/job.go#L99

Regards.

### PR DESCRIPTION
**Pull request by jrasell**
closes #653

### CODE REVIEW

**Review by pkazmierczak — APPROVED** [review]

File: plugins/builtin/apm/nomad/plugin/job.go [hunk 1]
```diff
@@ -79,7 +79,7 @@ func (a *APMPlugin) getTaskGroupResourceUsage(query *taskGroupQuery) ([]float64,
 		// does not vary between allocations.
 		allocatedCPU, err := a.getAllocatedCPUForTaskGroup(query.job, query.group)
 		if err != nil {
-			return nil, fmt.Errorf("failed to get total alloacted CPU for taskgroup: %v", err)
+			return nil, fmt.Errorf("failed to get total alloctaed CPU for taskgroup: %v", err)
```
Comment (Juanadelacuesta) [inline plugins/builtin/apm/nomad/plugin/job.go:82]:
```suggestion
			return nil, fmt.Errorf("failed to get total allocated CPU for taskgroup: %v", err)
```
