### PR TITLE
Recover file policies after manager soft-restarts (from Nomad API errors)

### LINKED ISSUE #519: Failed to get policy (EOF)
Hi folks,

Seeing some more errors and Nomad jobs that should definitely be triggering scaling are not happening. 

https://gist.github.com/evandam/4956199b01cd4303873b69cf7d3779c1

My first thought is that the Nomad agent is having issues, but it seems okay and I'm able to hit the same endpoints in the logs directly on the host 🤷‍♂️ 

As a side note, is there a decent way to debug things? There's `policy_id` in logs but I'm not sure how that maps back to the actual policy or Nomad job in question. It seems like it would be very helpful to be able to trace these back.

We're running Nomad 1.1.2 for what it's worth.

Any thoughts?

### PR DESCRIPTION
**Pull request by gulducat**
Fixes #519 "failed to read policy in time" errors, at least those which occur due to Handlers getting re-started, but then not receiving file policies, because they already exist from the point of view of the file policy Source.

When the policy Manager creates and runs new Handlers, the new Handler needs to receive a policy on its h.ch, or h.handleTick() will have a nil currentPolicy, which results in "timeout: failed to read policy in time"

So, each time Handler asks a Source to MonitorPolicy(), the Source needs to send a policy back to the Handler (via MonitorPolicyReq.ResultCh: h.ch), even if the Source already knows the policy from a previous run.

---

I want to acknowledge that, after I banged my head against it for awhile, I found that @Seros totally had a handle (heh) on it already in #625, but here I am anyway, having addressed the bug in a slightly different way.

The only real difference in behavior here is to retain the changed-or-not distinction when a reload signal is issued, which is probably trivial performance-wise, but I think nice to have in the logs.

Regardless, I've added @Seros as a co-author, since they also fixed it, months ago. :yum:  Also feel free to verify this change, if you'd like, and let me know how it goes!

### CODE REVIEW

File: policy/file/source.go [hunk 1]
```diff
@@ -214,15 +215,15 @@ func (s *Source) handleIndividualPolicyRead(ID policy.PolicyID, path, name strin
...
 	}
 
 	// Check the new policy against the stored. If they are the same, and
 	// therefore the policy has not changed indicate that to the caller.
 	if reflect.DeepEqual(newPolicy, val.policy) {
-		return nil, nil
+		return newPolicy, false, nil
 	}
-	return newPolicy, nil
+	return newPolicy, true, nil
```
Comment (jrasell) [inline policy/file/source.go:226]: Just spitballing, but this could potentially be written:
```
return newPolicy, !reflect.DeepEqual(newPolicy, val.policy), nil
```

**Review by jrasell — APPROVED** [review]
LGTM!

File: policy/file/source.go [hunk 2]
```diff
@@ -131,14 +131,15 @@ func (s *Source) MonitorPolicy(ctx context.Context, req policy.MonitorPolicyReq)
...
-		p, err := s.handleIndividualPolicyRead(req.ID, file, name)
+		p, _, err := s.handleIndividualPolicyRead(req.ID, file, name)
 		if err != nil {
-			policy.HandleSourceError(s.Name(), fmt.Errorf("failed to get policy %s", req.ID), req.ErrCh)
-		}
-		if p != nil {
-			req.ResultCh <- *p
-			s.policyMap[req.ID] = &filePolicy{file: file, name: name, policy: p}
+			policy.HandleSourceError(s.Name(), fmt.Errorf("failed to get policy %s: %w", req.ID, err), req.ErrCh)
+			return
```
[the remark this answers is not in the document]
Comment (gulducat) [reply policy/file/source.go]: how's 30ee9bb3813cbe4c8e267df645ba4c19b7339887 look to ya?

File: policy/file/source_test.go [hunk 3]
```diff
@@ -51,3 +55,158 @@ func TestSource_getFilePolicyID(t *testing.T) {
...
+
+	// running MonitorPolicy() twice should have the same result.
+	for _, n := range []string{"round one", "round two"} {
+
+		// not using sub-tests here, because if round one fails,
+		// there's no sense running round two.
+		// this little helper gives context for any failures.
+		fatal := func(msg string, args ...any) {
+			t.Helper()
+			t.Fatalf(n+": "+msg, args...)
```
Comment (lgfa29) [inline policy/file/source_test.go:94]: Probably not too relevant for a test, but I think this can cause the `go s.MonitorPolicy(ctx, req)` goroutine to leak. You could register a `t.Cleanup(cancel)` below to make sure the context is cancelled when the test exits.

File: policy/file/source_test.go
Comment (lgfa29) [inline policy/file/source_test.go:1]: Nice job with these test!

**Review by lgfa29 — APPROVED** [review]
Good work getting to the bottom of this. Also reiterating the big thanks to @Seros for fixing it a while ago!

File: policy/file/source.go (hunk 2 above)
[the remark this answers is not in the document]
Comment (lgfa29) [reply policy/file/source.go]: Looks good! The overall design of error handling feels questionable in hindsight, but that's my fault 😬
